### PR TITLE
Codifying Bill and Revision as types, rather than dictionaries

### PR DESCRIPTION
**Pull request by bruce-j-bland**
## What I did
Part one in a refactor effort to introduce testability and types to the backend.
This step enforces a type on Revisions and Bills as a first step in cleaning things up.

This change should not impact functionality at all.

## Why I did it
Python Dictionaries are very unsafe to hold structured data, especially in projects with multiple developers. Turning them into classes will make it easier for code legibility and type safety.

### CODE REVIEW

**Comment by maxachis** [comment]
**APPROVED AFTER CHANGE**: Code works as intended, but there's a concern with having the import statement in rss_etl.py being a relative statement, and I want to see if that might require a change to the rss_and_docx_etl.yaml workflow. 

I wasn't able to get rss_etl.py running right away -- running it as before yielded an error of ""ImportError: attempted relative import with no known parent package". Changing the ".common" in line 6 of rss_etl.py to "common" resolved this, as did changing  the script to run as "python -m law_reader.rss_etl" rather than "python law_reader/rss_etl.py".

The issue is that in [rss_and_docx_etl.yaml, in line 27](https://github.com/CodeForPittsburgh/law-reading-robot-data/blob/master/.github/workflows/rss_and_docx_etl.yaml#L27), the script is run as "python law_reader/rss_etl.py". It's unclear to me if the import error I ran into is unique to my own configuration or would also occur in this github action. 

Thus, I'd approve this after any of the following occur:

1. The ".common" in rss_etl.py is changed to "common".
2. Line 27 is changed to the "python -m law_reader.rss_etl" format (assuming this would prevent the issue).
3. Or it's explained to me that no change would be needed in the Github action, and the action should still run as expected without any change to the associated yaml file.

2/3 would be easier if we can run Github Actions locally, and I have [a task on Trello](https://trello.com/c/6qpcgyhB/63-look-into-act-to-test-github-actions-locally) that does aim to address that. As is, 1 is probably the easiest. 

I'll also say I'm not as familiar with relative imports within packages, so my apologies for where my own ignorance adds to this.

**Review by maxachis — CHANGES_REQUESTED** [review]
**APPROVED AFTER CHANGE**: Code works as intended, but there's a concern with having the import statement in rss_etl.py being a relative statement, and I want to see if that might require a change to the rss_and_docx_etl.yaml workflow. 

I wasn't able to get rss_etl.py running right away -- running it as before yielded an error of ""ImportError: attempted relative import with no known parent package". Changing the ".common" in line 6 of rss_etl.py to "common" resolved this, as did changing  the script to run as "python -m law_reader.rss_etl" rather than "python law_reader/rss_etl.py".

The issue is that in [rss_and_docx_etl.yaml, in line 27](https://github.com/CodeForPittsburgh/law-reading-robot-data/blob/master/.github/workflows/rss_and_docx_etl.yaml#L27), the script is run as "python law_reader/rss_etl.py". It's unclear to me if the import error I ran into is unique to my own configuration or would also occur in this github action. 

Thus, I'd approve this after any of the following occur:

1. The ".common" in rss_etl.py is changed to "common".
2. Line 27 is changed to the "python -m law_reader.rss_etl" format (assuming this would prevent the issue).
3. Or it's explained to me that no change would be needed in the Github action, and the action should still run as expected without any change to the associated yaml file.

2/3 would be easier if we can run Github Actions locally, and I have [a task on Trello](https://trello.com/c/6qpcgyhB/63-look-into-act-to-test-github-actions-locally) that does aim to address that. As is, 1 is probably the easiest. 

I'll also say I'm not as familiar with relative imports within packages, so my apologies for where my own ignorance adds to this.

**Comment by bruce-j-bland** [comment]
> **APPROVED AFTER CHANGE**: Code works as intended, but there's a concern with having the import statement in rss_etl.py being a relative statement, and I want to see if that might require a change to the rss_and_docx_etl.yaml workflow.

Some of this is bad habits from javascript. But it really comes down to package management, potential package name collisions, and pycharm bugs.

It's an annoying situation I don't really want to get into, but the long and short is that none of those suggested changes work, as they will break the IDE connection or will break unit tests, but the one I implemented will get all of it working again.

You will need to add '.' to PYTHONPATH to get things to work now.

**Review by maxachis — APPROVED** [review]
Works as expected now! We're good to go 🐎,

**Pull request merged**
